import React, { useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';

// --- SHARED LAYOUT HELPER ---
const PageLayout = ({ title, children }) => (
  <div className="min-h-screen bg-slate-50 p-6 md:p-12 font-sans text-slate-800">
    <div className="max-w-4xl mx-auto bg-white p-8 md:p-16 rounded-3xl shadow-xl border border-slate-100">
      <Link to="/" className="inline-block mb-8 text-sm font-bold text-indigo-600 hover:text-indigo-800 transition">
        ← Back to Home
      </Link>
      <h1 className="text-4xl font-black text-slate-900 mb-8 tracking-tight">{title}</h1>
      {children}
    </div>
  </div>
);

// ==========================================
// 1. PRIVACY POLICY
// ==========================================
export const PrivacyPolicy = () => (
  <PageLayout title="Privacy Policy">
    <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed">
      <p className="mb-4">Last Updated: {new Date().getFullYear()}</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">1. Data Collection</h3>
      <p>We collect essential information required for timetable generation, including teacher names, emails, subject lists, and classroom details. We do not share this data with third parties.</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">2. Usage of Information</h3>
      <p>Your data is used exclusively for: <br />- Generating academic schedules <br />- User authentication <br />- System optimization analytics</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">3. Data Security</h3>
      <p>We implement industry-standard security measures, including HTTP-Only cookies for session management and encrypted password storage.</p>
      <div className="mt-12 pt-8 border-t border-slate-200 text-sm text-slate-400"> <span className="text-xl font-bold tracking-tight ">
        <span className="text-indigo-600">Tima</span>
        <span className="text-slate-800"> - Timetable </span>
        <button className="
  px-2
  text-white 
  font-bold 
  rounded-full 
  shadow-lg 
  bg-gradient-to-r from-indigo-600 to-purple-600
  hover:from-indigo-700 hover:to-purple-700
  transition transform hover:-translate-y-4
">
          GENAI
        </button>

      </span> © {new Date().getFullYear()}</div>
    </div>
  </PageLayout>
);

// ==========================================
// 2. TERMS OF SERVICE
// ==========================================
export const TermsOfService = () => (
  <PageLayout title="Terms of Service">
    <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed">
      <p className="mb-4">By accessing TimetableAI, you agree to these terms.</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">1. Acceptable Use</h3>
      <p>You agree to use this software only for educational and administrative scheduling purposes. Misuse or attempts to disrupt the service are prohibited.</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">2. Account Responsibility</h3>
      <p>You are responsible for maintaining the confidentiality of your School ID and login credentials.</p>
      <h3 className="text-xl font-bold text-slate-800 mt-6 mb-2">3. Limitation of Liability</h3>
      <p>TimetableAI is provided "as is". We are not liable for any academic disruptions caused by scheduling errors generated by the AI.</p>
      <div className="mt-12 pt-8 border-t border-slate-200 text-sm text-slate-400"> <span className="text-xl font-bold tracking-tight ">
        <span className="text-indigo-600">Tima</span>
        <span className="text-slate-800"> - Timetable </span>
        <button className="
  px-2
  text-white 
  font-bold 
  rounded-full 
  shadow-lg 
  bg-gradient-to-r from-indigo-600 to-purple-600
  hover:from-indigo-700 hover:to-purple-700
  transition transform hover:-translate-y-4
">
          GENAI
        </button>

      </span> © {new Date().getFullYear()}</div>
    </div>
  </PageLayout>
);

// ==========================================
// 3. CONTACT SUPPORT
// ==========================================
export const ContactSupport = () => {
  const [form, setForm] = useState({ email: '', phone: '', issue: '' });
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      // POST to your backend (Ensure route exists)
      await axios.post('http://localhost:5000/api/support', form);
      alert("✅ Ticket Created! Our team will contact you shortly.");
      setForm({ email: '', phone: '', issue: '' });
    } catch (err) {
      alert("❌ Error sending request. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageLayout title="Contact Support">
      <form onSubmit={handleSubmit} className="space-y-6 max-w-lg">
        <div>
          <label className="block text-sm font-bold text-slate-700 mb-2">Email Address</label>
          <input type="email" required className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
            value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@university.edu" />
        </div>
        <div>
          <label className="block text-sm font-bold text-slate-700 mb-2">Contact Number</label>
          <input type="tel" required className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
            value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="+91 98765 43210" />
        </div>
        <div>
          <label className="block text-sm font-bold text-slate-700 mb-2">Describe the Issue</label>
          <textarea required rows="4" className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none"
            value={form.issue} onChange={e => setForm({ ...form, issue: e.target.value })} placeholder="Tell us what went wrong..." />
        </div>
        <button disabled={loading} className="w-full py-4 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl transition shadow-lg shadow-indigo-200">
          {loading ? 'Sending...' : 'Submit Ticket'}
        </button>
      </form>
    </PageLayout>
  );
};

// ==========================================
// 4. FEEDBACK FORM
// ==========================================
export const Feedback = () => {
  const [answers, setAnswers] = useState({ q1: '', q2: '', q3: '', q4: '', q5: '', comments: '' });
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      // POST to backend
      await axios.post('http://localhost:5000/api/feedback', answers);
      alert("✅ Thank you for your feedback!");
      setAnswers({ q1: '', q2: '', q3: '', q4: '', q5: '', comments: '' });
    } catch (err) {
      alert("❌ Error submitting feedback.");
    } finally {
      setLoading(false);
    }
  };

  const RadioGroup = ({ question, name, options }) => (
    <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
      <p className="font-bold text-slate-800 mb-4">{question}</p>
      <div className="grid grid-cols-2 gap-3">
        {options.map(opt => (
          <label key={opt} className={`flex items-center gap-3 cursor-pointer p-3 rounded-xl border transition-all ${answers[name] === opt ? 'bg-emerald-50 border-emerald-500 text-emerald-700' : 'bg-slate-50 border-slate-200 hover:border-slate-300'}`}>
            <input type="radio" name={name} value={opt} checked={answers[name] === opt} onChange={(e) => setAnswers({ ...answers, [name]: e.target.value })} className="accent-emerald-600 w-4 h-4" />
            <span className="text-sm font-medium">{opt}</span>
          </label>
        ))}
      </div>
    </div>
  );

  return (
    <PageLayout title="We Value Your Feedback">
      <form onSubmit={handleSubmit} className="space-y-6">
        <RadioGroup question="1. How fast was the timetable generation?" name="q1" options={["⚡ Very Fast", "👌 Average", "🐢 Slow", "❌ Failed"]} />
        <RadioGroup question="2. How accurate was conflict handling?" name="q2" options={["💎 Perfect", "👍 Good", "👎 Poor"]} />
        <RadioGroup question="3. Is the interface easy to use?" name="q3" options={["😃 Very Easy", "😐 Okay", "😵 Confusing"]} />
        <RadioGroup question="4. Did the AI follow department rules?" name="q4" options={["✅ Yes", "❌ No", "🤔 Not Sure"]} />

        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
          <p className="font-bold text-slate-800 mb-4">5. Overall Rating</p>
          <div className="flex gap-2">
            {[1, 2, 3, 4, 5].map(n => (
              <button key={n} type="button" onClick={() => setAnswers({ ...answers, q5: n.toString() })} className={`flex-1 py-3 rounded-xl font-bold border transition ${answers.q5 === n.toString() ? 'bg-emerald-600 text-white border-emerald-600' : 'bg-slate-50 border-slate-200 text-slate-500 hover:bg-slate-100'}`}>
                {n}★
              </button>
            ))}
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm">
          <p className="font-bold text-slate-800 mb-4">6. Any suggestions?</p>
          <textarea className="w-full p-4 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-emerald-500 h-32" placeholder="Type here..." value={answers.comments} onChange={e => setAnswers({ ...answers, comments: e.target.value })}></textarea>
        </div>

        <button disabled={loading} className="w-full py-4 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl transition shadow-lg shadow-emerald-200">
          {loading ? 'Submitting...' : 'Submit Feedback'}
        </button>
      </form>
    </PageLayout>
  );
};